version: '3'

services:
  scam-hunter-bot:
    build: 
      context: .
      dockerfile: Dockerfile.bot
    container_name: scam-hunter
    restart: unless-stopped
    networks:
      - scam-hunter-bot-network
    volumes:
      - ./settings.json:/home/node/app/settings.json:ro
      - ./firebase.json:/home/node/app/firebase.json:ro
  scam-hunter-site:
    build:
      context: .
      dockerfile: Dockerfile.site
    container_name: scam-hunter-site
    restart: unless-stopped
    #ports:
    #  - '5007:80'
    volumes:
      - ./settings.json:/home/node/app/settings.json:ro
      - ./firebase.json:/home/node/app/firebase.json:ro
  scam-hunter-site-tunnel:
    image: cloudflare/cloudflared
    container_name: scam-hunter-site-tunnel
    restart: unless-stopped
    command: tunnel run
    env_file:
      - .env
    depends_on:
      - scam-hunter-site

networks:
  scam-hunter-bot-network:
  default:
    name: scam-hunter-site
    external: true