version: '3'

services:
  scam-hunter-bot:
    build: 
      context: .
      dockerfile: Dockerfile.bot
    container_name: scam-hunter
    restart: unless-stopped
    networks:
      - scam-hunter-bot-network
    volumes:
      - ./settings.json:/home/node/app/settings.json:ro
      - ./firebase.json:/home/node/app/firebase.json:ro
  scam-hunter-site:
    build:
      context: .
      dockerfile: Dockerfile.site
    container_name: scam-hunter-site
    restart: unless-stopped
    networks:
      - scam-hunter-site-network
    ports:
      - '5007:80'
    volumes:
      - ./settings.json:/home/node/app/settings.json:ro
      - ./firebase.json:/home/node/app/firebase.json:ro

networks:
  scam-hunter-bot-network:
  scam-hunter-site-network: