FROM node:20-alpine

LABEL org.opencontainers.image.title="Scam Hunter Site" \
      org.opencontainers.image.description="Review findings of the Scam Hunter Bot" \
      org.opencontainers.image.authors="@shane on Discord"

RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app

WORKDIR /home/node/app

COPY . .

USER node

COPY --chown=node:node . .

RUN npm install
RUN npm audit fix 2>1

ENTRYPOINT ["node", "server.js"]